# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 07:46
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='Agreement'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='Privacy'),
        ),
    ]
