# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='signature',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
