# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
