# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
