# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='img',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
