# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='remark',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
