# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_contactinfo_section_sectioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioninfo',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
