# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('sort', models.IntegerField(unique=True)),
                ('img', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abstract', models.CharField(max_length=150)),
                ('introduce', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('sort', models.IntegerField(unique=True)),
                ('img', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GBasePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('sort', models.IntegerField(unique=True)),
                ('basepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GBasePage')),
            ],
        ),
        migrations.CreateModel(
            name='GSectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200, null=True)),
                ('subtitle', models.CharField(max_length=200, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Languages')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GSection')),
            ],
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Games'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Languages'),
        ),
    ]
